In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.decomposition import PCA

### 3個六維資料

In [3]:
pca = PCA(n_components=0.95)
data = pca.fit_transform([[2,8,4,5,9,3], [6,3,0,8,7,1], 
                          [5,4,9,1,8,2]])

### 6維降為2維

In [5]:
print(data)

[[-0.27506139  4.0732061 ]
 [ 5.92362693 -1.89137796]
 [-5.64856554 -2.18182813]]


In [6]:
prior = pd.read_csv('order_products__prior.csv')
products = pd.read_csv('products.csv')
orders = pd.read_csv('orders.csv')
aisles = pd.read_csv('aisles.csv')
t1 = pd.merge(prior, products, on=['product_id', 
                                   'product_id'])
t1 = pd.merge(t1, orders, on=['order_id', 'order_id'])
mt = pd.merge(t1, aisles, on=['aisle_id', 'aisle_id'])
print(mt.shape)
mt

(32434489, 14)


order_id  product_id  add_to_cart_order  reordered  \
0                2       33120                  1          1   
1               26       33120                  5          0   
2              120       33120                 13          0   
3              327       33120                  5          1   
4              390       33120                 28          1   
...            ...         ...                ...        ...   
32434484   3243156       20731                  1          0   
32434485    860862       30582                  1          0   
32434486   1333472       27906                  1          0   
32434487   2122701       26086                  1          1   
32434488   3168475       26086                  1          1   

                          product_name  aisle_id  department_id  user_id  \
0                   Organic Egg Whites        86             16   202279   
1                   Organic Egg Whites        86             16   153404   
2                   Organic Egg Whites        86             16    23750   
3                   Organic Egg Whites        86             16    58707   
4                   Organic Egg Whites        86             16   166654   
...                                ...       ...            ...      ...   
32434484               Straight Sherry       134              5   166400   
32434485             Natural Champagne       134              5   104017   
32434486            Imperial Champagne       134              5    62079   
32434487  La Grand Dame Brut Champagne       134              5    77799   
32434488  La Grand Dame Brut Champagne       134              5     5223   

         eval_set  order_number  order_dow  order_hour_of_day  \
0           prior             3          5                  9   
1           prior             2          0                 16   
2           prior            11          6                  8   
3           prior            21          6                  9   
4           prior            48          0                 12   
...           ...           ...        ...                ...   
32434484    prior             3          1                 13   
32434485    prior            13          5                 14   
32434486    prior            10          3                 10   
32434487    prior             2          3                 14   
32434488    prior             7          3                 13   

          days_since_prior_order                       aisle  
0                            8.0                        eggs  
1                            7.0                        eggs  
2                           10.0                        eggs  
3                            8.0                        eggs  
4                            9.0                        eggs  
...                          ...                         ...  
32434484                    12.0  specialty wines champagnes  
32434485                    18.0  specialty wines champagnes  
32434486                    10.0  specialty wines champagnes  
32434487                     3.0  specialty wines champagnes  
32434488                     2.0  specialty wines champagnes  

[32434489 rows x 14 columns]

In [7]:
cross = pd.crosstab(mt['user_id'], mt['aisle'])
print(cross.shape)
cross

(206209, 134)


aisle    air fresheners candles  asian foods  baby accessories  \
user_id                                                          
1                             0            0                 0   
2                             0            3                 0   
3                             0            0                 0   
4                             0            0                 0   
5                             0            2                 0   
...                         ...          ...               ...   
206205                        0            0                 1   
206206                        0            4                 0   
206207                        0            0                 0   
206208                        0            3                 0   
206209                        0            1                 0   

aisle    baby bath body care  baby food formula  bakery desserts  \
user_id                                                            
1                          0                  0                0   
2                          0                  0                0   
3                          0                  0                0   
4                          0                  0                0   
5                          0                  0                0   
...                      ...                ...              ...   
206205                     0                  0                0   
206206                     0                  0                0   
206207                     0                  1                0   
206208                     0                  3                0   
206209                     0                  0                0   

aisle    baking ingredients  baking supplies decor  beauty  beers coolers  \
user_id                                                                     
1                         0                      0       0              0   
2                         2                      0       0              0   
3                         0                      0       0              0   
4                         0                      0       0              0   
5                         0                      0       0              0   
...                     ...                    ...     ...            ...   
206205                    0                      0       0              0   
206206                    4                      1       0              0   
206207                    0                      0       0              0   
206208                    4                      0       0              0   
206209                    0                      0       0              0   

aisle    ...  spreads  tea  tofu meat alternatives  tortillas flat bread  \
user_id  ...                                                               
1        ...        1    0                       0                     0   
2        ...        3    1                       1                     0   
3        ...        4    1                       0                     0   
4        ...        0    0                       0                     1   
5        ...        0    0                       0                     0   
...      ...      ...  ...                     ...                   ...   
206205   ...        0    0                       0                     0   
206206   ...        1    0                       0                     0   
206207   ...        3    4                       0                     2   
206208   ...        5    0                       0                     7   
206209   ...        0    0                       0                     0   

aisle    trail mix snack mix  trash bags liners  vitamins supplements  \
user_id                                                                 
1                          0                  0                     0   
2                          0                  

In [19]:
pca = PCA(n_components=0.95)
data = pca.fit_transform(cross)
print(data.shape)

(206209, 44)


In [8]:
from sklearn.datasets import load_iris
iris = load_iris()

In [9]:
print('資料集描述：')
print(iris.DESCR)
print('特徵值：')
print(iris.data)
print('目標值：')
print(iris.target)
print('特徵名稱：')
print(iris.feature_names)
print('目標名稱：')
print(iris.target_names)

資料集描述：
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ====

In [10]:
from sklearn.datasets import fetch_20newsgroups
news = fetch_20newsgroups(data_home='.', subset='all')
print('目標值：')
print(news.target)
print('目標名稱：')
print(news.target_names)
print('第一篇新聞內容：')
print(news.data[0])  #列印第一篇新聞

目標值：
[10  3 17 ...  3  1  7]
目標名稱：
['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
第一篇新聞內容：
From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why


In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np
iris = load_iris()
x_train , x_test , y_train , y_test = train_test_split(
    iris.data,iris.target,test_size=0.2)
std = StandardScaler()
x_train = std.fit_transform(x_train)
x_test = std.transform(x_test)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_predict = knn.predict(x_test)
print('  目標值：{}'.format(y_test))
print('預測結果：{}'.format(y_predict))
print('  準確率：{}'.format(knn.score(x_test, y_test)))

  目標值：[2 0 2 2 0 1 0 1 0 0 2 1 1 0 2 0 0 2 1 0 0 1 0 0 2 0 0 2 1 2]
預測結果：[2 0 2 2 0 1 0 1 0 0 2 1 1 0 2 0 0 2 2 0 0 1 0 0 2 0 0 2 1 1]
  準確率：0.9333333333333333


In [18]:
from sklearn.neighbors import \
    KNeighborsClassifier
from sklearn.model_selection import \
    train_test_split
import numpy as np
import matplotlib.pyplot as plt

In [19]:
data = []
for i in range(10):
    for j in range(1,501):
        data.append(plt.imread('mnist500/%d/%d_%d.bmp'%(i,i,j)))
x = np.array(data)
print(x.shape)

(5000, 28, 28)


In [20]:
y = [0,1,2,3,4,5,6,7,8,9]*500
y = np.array(y)
y.sort()
print(y)

[0 0 0 ... 9 9 9]


In [25]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
data = []
for i in range(10):
    for j in range(1,1001):
        data.append(plt.imread('mnist1000/%d/%d_%d.bmp'%(i,i,j)))
x = np.array(data)
y = [0,1,2,3,4,5,6,7,8,9]*1000
y = np.array(y)
y.sort()

In [26]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train.reshape(8000,-1),y_train)
score = knn.score(x_test.reshape(2000,-1),y_test)
print(score)

0.948


In [23]:
import joblib
knnmodel = joblib.load('mnist500.pkl')
score = knnmodel.score(x_test.reshape(2000,-1),y_test)
print(score)

D:\python3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.0.2 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(


0.011


In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
data = cv.fit_transform(['code is easy, i like python', 
                         'code is too hard, i dislike python'])
#print(data)
print(data.toarray())
print(cv.get_feature_names_out()) #'CountVectorizer' object has no attribute 'get_feature_names_out'產生此問題

[[1 0 1 0 1 1 1 0]
 [1 1 0 1 1 0 1 1]]


AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names_out'

In [27]:
pip install jieba

Note: you may need to restart the kernel to use updated packages.


In [28]:
import jieba
t1 = list(jieba.cut('今天台北天氣晴朗，風景區擠滿了人潮。'))
t2 = list(jieba.cut('台北的天氣常常下雨。'))
c1 = ' '.join(t1)
c2 = ' '.join(t2)
print(c1)
print(c2)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\88697\AppData\Local\Temp\jieba.cache
Loading model cost 0.583 seconds.
Prefix dict has been built successfully.


今天 台北 天氣 晴朗 ， 風景區 擠 滿 了 人潮 。
台北 的 天氣 常常 下雨 。


In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
data = tf.fit_transform([c1, c2])
print(data.toarray())
print(cv.get_feature_names_out())

[[0.         0.44665616 0.44665616 0.31779954 0.31779954 0.
  0.44665616 0.44665616]
 [0.57615236 0.         0.         0.40993715 0.40993715 0.57615236
  0.         0.        ]]


AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names_out'

In [30]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
news = fetch_20newsgroups(subset='all')
x_train, x_test, y_train, y_test = train_test_split(
    news.data, news.target, test_size=0.20)
tf = TfidfVectorizer()
x_train = tf.fit_transform(x_train)  
x_test = tf.transform(x_test)
mlt = MultinomialNB(alpha=1.0)
mlt.fit(x_train, y_train)
score = mlt.score(x_test, y_test)
print(score)

0.8527851458885941


In [31]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import jieba
f = open('toutiao_cat_data.txt',encoding='utf-8')
data = []
target = []
for line in f:
  linelist = line.split('_!_')
  target.append(linelist[1])
  tem = list(jieba.cut(linelist[3]))
  data.append(' '.join(tem))
x_train, x_test, y_train, y_test = train_test_split(
    data, target, test_size=0.20)
tf = TfidfVectorizer()
x_train = tf.fit_transform(x_train)  
x_test = tf.transform(x_test)
mlt = MultinomialNB(alpha=1.0)
mlt.fit(x_train, y_train)
score = mlt.score(x_test, y_test)
print(score)

0.8296924403564243


In [32]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

df = pd.read_csv('titanic.csv')
x = df[['pclass', 'age', 'sex']]
y = df['survived']
x['age'].fillna(x['age'].mean(), inplace=True) #空值填充
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2)
dict = DictVectorizer(sparse=False)
x_train = x_train.to_dict(orient='records')
x_train = dict.fit_transform(x_train)
x_test = x_test.to_dict(orient='records')
x_test = dict.transform(x_test)
print('訓練資料：')
print(x_train)
print('onehot 特徵名稱：')
print(dict.get_feature_names_out())

訓練資料：
[[31.19418104  0.          0.          1.          0.          1.        ]
 [ 8.          0.          1.          0.          1.          0.        ]
 [31.19418104  0.          0.          1.          1.          0.        ]
 ...
 [31.19418104  0.          0.          1.          0.          1.        ]
 [14.          0.          1.          0.          0.          1.        ]
 [22.          0.          1.          0.          1.          0.        ]]
onehot 特徵名稱：


D:\python3\lib\site-packages\pandas\core\generic.py:6392: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


AttributeError: 'DictVectorizer' object has no attribute 'get_feature_names_out'

In [33]:
dec = DecisionTreeClassifier()
dec.fit(x_train, y_train)
score = dec.score(x_test, y_test)
print(score)

0.8288973384030418


In [34]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

df = pd.read_csv('wine.csv')
x = df.iloc[:, 1:14]
y = df.iloc[:, 0]
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2)
rf = RandomForestClassifier(n_estimators=10, 
                            min_samples_split=30)
rf.fit(x_train, y_train)
score = rf.score(x_test, y_test)
print(score)

1.0
